package com.scheduler.model;

import java.sql.Timestamp;

public class Booking {
    private int bookingId;
    private int roomId;
    private String organizer;
    private Timestamp startTime;
    private Timestamp endTime;

    // Constructor for creating a new booking (ID is auto-generated by DB)
    public Booking(int roomId, String organizer, Timestamp startTime, Timestamp endTime) {
        this.roomId = roomId;
        this.organizer = organizer;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    // Getters
    public int getBookingId() { return bookingId; }
    public int getRoomId() { return roomId; }
    public String getOrganizer() { return organizer; }
    public Timestamp getStartTime() { return startTime; }
    public Timestamp getEndTime() { return endTime; }

    // Setters
    public void setBookingId(int bookingId) { this.bookingId = bookingId; }
    public void setRoomId(int roomId) { this.roomId = roomId; }
    public void setOrganizer(String organizer) { this.organizer = organizer; }
    public void setStartTime(Timestamp startTime) { this.startTime = startTime; }
    public void setEndTime(Timestamp endTime) { this.endTime = endTime; }
}
